### PR TITLE
Update lab1.rst

### PR DESCRIPTION
**Pull request by vtog**
need to update for lab IP changes

### CODE REVIEW

**Comment by jmcalalang** [comment]
Vince was this me? you doing this against the new BP?

**Comment by vtog** [comment]
I haven't looked at your BP yet, was going to do that Monday....this was for the original UDF lab and the stuff I built.  I wanted everything to match the lab topology spelled out on the guide....I assumed you would be matching that as well.

**Comment by jmcalalang** [comment]
ok i think in the Ravello BP i actually kept the old addresses 10.1.10.10, so the documentation should still be correct. 

screen shot 2017-04-28 at 8 24 34 pm

We should just fix the UDF 2.0 lamp server, then both environments are in sync. what we need here is the other devices in the environment as code, so we can push it to everything in one shot.

**Comment by vtog** [comment]
Yep...the v2 doc changed all this, I'm guessing for UDF.  Since this exists in both, Ravello and UDF I thought it easier to just change my old BP.  Either way works for me.  I'll leave it up to you and Hitesh on how you want to handle this.  All I care about is consistency between all the environments and lab guide.

**Comment by vtog** [comment]
cancel...decision to use original IP addressing

**Pull request closed without merging**
